### ISSUE TITLE
Media Technology Data Handling

### ISSUE THREAD

**Issue by pinterid** [snek-at/intel#105]
**User Story**
As a user I want to be able to represent images, videos & music on my profile, in order to show others my activity in the media technology world.

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to provide handling of images, videos or music data for an SNEK profile.

**Describe the solution you'd like**
It should be possible to provide handling of images, videos and music data for an SNEK profile.

Solutions that could be implemented:
-  Intel save functionality for links block with meta tags.
-  Intel save functionality for url collection with meta tags.
-  Intel Imgur API util.
-  Implement Instagram API prototype in intel.
-  Implement SoundCloud API prototype in intel.
-  Adjust profile with links blocks with meta tags.
-  Adjust profile with image url collection with meta tags.

**Requirements**
- [ ] Instagram Data Concept. #92 
- [ ] Instagram Data Prototype. #93 
- [ ] SoundCloud Data Concept. #108
- [ ] SoundCloud Data Prototype. #109 

**Milestones**
<table>
   <tbody>
      <tr>
         <th align="left" width=200px><b>Feature Milestones</b></th>
         <th align="left" width=250px>Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Feature Designed</td>
         <td>Wed, 19 Aug 2020 10:45:56 +0200</td>
      </tr>
      <tr>
         <td>Requirements Fulfilled</td>
         <td></td>
      </tr>
      <tr>
         <td>Feature Reviewed</td>
         <td></td>
      </tr>
      <tr>
         <th align="left"><b>Opportunity Milestones</b></th>
         <th align="left">Completed at in RFC 2822 format</th>
      </tr>
      <tr>
         <td>Implementation Done</td>
         <td></td>
      </tr>
      <tr>
         <td>Implementation Reviewed</td>
         <td></td>
      </tr>
      <tr>
         <td>Implementation Deployed</td>
         <td></td>
      </tr>
   </tbody>
</table>
